name: Dispatch Playwright Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests against'
        required: true
        type: string
        default: 'qa'
      tag:
        description: 'Tag to filter tests'
        required: true
        type: string
        default: 'e2e'
      playwright_repo:
        description: 'Playwright Automation Repository'
        required: true
        type: string
        default: 'afonte15/playwright-demo'
      playwright_repo_ref:
        description: 'Branch or commit to use in the Playwright repository'
        required: false
        type: string
        default: 'main'
      run_command:
        description: 'Command to run the Playwright tests'
        required: true
        type: string
        default: 'npx playwright test'

permissions:
  contents: write

jobs:
  dispatch-playwright-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Run Tagged Playwright Tests
      uses: afonte15/playwright-cicd/.github/workflows/run-tagged-tests.yml@main
      with:
        tag: ${{ github.event.inputs.tag || 'e2e' }}
        playwright_repo: ${{ github.event.inputs.playwright_repo || 'afonte15/playwright-demo' }}
        playwright_repo_ref: ${{ github.event.inputs.playwright_repo_ref || 'main' }}
        environment: ${{ github.event.inputs.environment || 'qa' }}
        run_command: ${{ github.event.inputs.run_command || 'npx playwright test' }}
      env:
        REPO_GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN  }}
        QA_BASE_URL: ${{ secrets.QA_BASE_URL }}
        QA_ENVIRONMENT: ${{ secrets.QA_ENVIRONMENT }}
        STAGING_BASE_URL: ${{ secrets.STAGING_BASE_URL }}
        STAGING_ENVIRONMENT: ${{ secrets.STAGING_ENVIRONMENT }}
