name: Dispatch Playwright Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dispatch-playwright-tests:
    uses: afonte15/playwright-cicd/.github/workflows/run-tagged-tests.yml@main
    with:
      tag: 'e2e'
      playwright_repo: 'afonte15/playwright-demo'
      playwright_repo_ref: 'main'
      run_command: 'npx playwright test --grep @'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
