name: Dispatch Playwright Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests against'
        required: true
        type: string
        default: 'qa'
      tag:
        description: 'Tag to filter tests'
        required: true
        type: string
        default: 'e2e'
      playwright_repo:
        description: 'Playwright Automation Repository'
        required: true
        type: string
        default: 'afonte15/playwright-automation'
      playwright_repo_ref:
        description: 'Branch or commit to use in the Playwright repository'
        required: false
        type: string
        default: 'main'
      run_command:
        description: 'Command to run the Playwright tests'
        required: true
        type: string

permissions:
  contents: write

jobs:
  dispatch-playwright-tests:
    uses: afonte15/playwright-cicd/.github/workflows/run-tagged-tests.yml@main
    with:
      tag: ${{ github.event.inputs.tag }}
      playwright_repo: ${{ github.event.inputs.playwright_repo }}
      playwright_repo_ref: ${{ github.event.inputs.playwright_repo_ref }}
      environment: ${{ github.event.inputs.environment }}
      run_command: ${{ github.event.inputs.run_command }}
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      QA_BASE_URL: ${{ secrets.QA_BASE_URL }}
      QA_ENVIRONMENT: ${{ secrets.QA_ENVIRONMENT }}
      STAGING_BASE_URL: ${{ secrets.STAGING_BASE_URL }}
      STAGING_ENVIRONMENT: ${{ secrets.STAGING_ENVIRONMENT }}
