name: Dispatch to Playwright Automation Repo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - staging
          - production
      tags:
        description: 'Select the test tags'
        required: true
        default: '@e2e'
        type: choice
        options:
          - '@e2e'
          - '@smoke'
          - '@regression'

permissions:
  contents: read
  actions: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to Playwright Automation Repo
        uses: afonte15/playwright-cicd@main
        with:
          repo: 'afonte15/playwright-automation' 
          event-type: 'run-tests'  
          client-payload: '{"env": "${{ github.event.inputs.environment }}", "grep": "${{ github.event.inputs.tags }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
