name: Create Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - staging
          - production
      tags:
        description: 'Select the test tags'
        required: true
        default: '@e2e'
        type: choice
        options:
          - '@e2e'
          - '@smoke'
          - '@regression'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repo
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'afonte15',  # Replace with the owner of Repo B
              repo: 'playwright-demo',  # Replace with the name of Repo B
              workflow_id: 'run-playwright-tests.yml',  # The name of the workflow file in Repo B
              ref: 'main',  # The branch to run the workflow on
              inputs: {
                environment: '${{ github.event.inputs.environment }}',
                tags: '${{ github.event.inputs.tags }}'
              }
            })
