name: Upload Test Configuration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - staging
          - production
      tags:
        description: 'Select the test tags'
        required: true
        default: '@e2e'
        type: choice
        options:
          - '@e2e'
          - '@smoke'
          - '@regression'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create test config file
        run: |
          echo '{"environment": "${{ github.event.inputs.environment }}", "tags": "${{ github.event.inputs.tags }}"}' > test-config.json

      - name: Upload test config
        uses: actions/upload-artifact@v2
        with:
          name: test-config
          path: test-config.json
